tasks:
  - name: Setup MySQL
    init: |
      sudo apt-get update
      sudo apt-get install -y mysql-server mysql-client
      sudo mkdir -p /workspace/mysql-data /workspace/mysql-logs
      sudo mysqld_safe --datadir=/workspace/mysql-data \
                       --log-error=/workspace/mysql-logs/error.log \
                       --pid-file=/workspace/mysql-logs/mysql.pid \
                       --skip-grant-tables \
                       --skip-networking=0 \
                       --bind-address=0.0.0.0 &
    command: |
      echo "MySQL está rodando"
      mysql --version

ports:
  - port: 3306
    onOpen: ignore

