
tasks:
  - command: python app.py



vscode:
  extensions:
    - mtxr.sqltools-driver-sqlites (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
    - mtxr.sqltools-driver-sqlite# and commit this file to your remote git repository to share the goodness with others.
    - mtxr.sqltools-driver-sqlite# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
    - mtxr.sqltools-driver-sqlitetasks:
    - mtxr.sqltools-driver-sqlite  - command: python app.py
    - mtxr.sqltools-driver-sqlite
    - mtxr.sqltools
